# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b1c83ae0c7090f41a4662c1786bd098716d4b6c1f6c2b499436b4af0bab228f9c12aa93312b95f03a65f6da54e1d7fec798ff4c36015b15c9449b6717a5124c

test:
  secret_key_base: 15d2ff18fe603a9a282109a3d75a7bf7603d457bc0bba625b52cd59c2b5c84271985c5b7f8987c8c7122873f9aab4b0f085f3122dcdad4293a7a97cf20c35fca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
